[package]
name = "smart_crest"
version = "0.1.0"
authors = ["haslersn <sebastian.hasler@gmx.net>"]
edition = "2018"

[dependencies]
env_logger = "0.6"
hex = "0.3"
log = "0.4"
reqwest = "0.9"
pcsc = "2.1"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
